= JupyterLab でサンプル ワークロードを実行する
:experimental:
:page-author: Thripti Aravind
:page-email: thripti.aravind@teradata.com
:page-revdate: 2023 年 4 月 10 日
:description: 簡単なワークフローを実行し、Regulus の使用方法を学びます。
:keywords: Regulus、ワークスペース、クエリーエンジン

IMPORTANT: この製品はプレビュー段階にあり、変更される可能性があります。Regulus に早期アクセスするには、サポートにお問い合わせください。

== 概要

このドキュメントでは、JupyterLab を使用して次のことを行うための簡単なワークフローについて説明します。

* オンデマンドでスケーラブルなコンピューティングを導入する
* 外部データソースに接続する
* ワークロードを実行する
* コンピューティングを一時停止する

== 始める前に

* Regulus をインストールして設定します。 xref::jp/regulus/install-regulus-docker-image.adoc[]を参照してください。

* 以下をコピーして保持します。

** AWS コンソールからの AWS 環境変数 `AWS_ACCESS_KEY_ID`、 `AWS_SECRET_ACCESS_KEY`、および `AWS_SESSION_TOKEN` 。 link:https://docs.aws.amazon.com/sdkref/latest/guide/environment-variables.html[「環境変数」]を参照してください。
** ワークスペースからの API キー。

== 最初のワークロードを実行する

マジック コマンドの詳細については、 `%help` または `%help <command>` を実行してください。詳細については xref::jp/regulus/regulus-magic-reference.adoc[] を参照してください。

1. URL: http://localhost:8888 を使用して JupyterLab に接続し、プロンプトが表示されたらトークンを入力します。
2. API キーを使用してワークスペースに接続します。
+
[source, bash, id="connect_workspaces", role="content-editable emits-gtm-events"]
----
%workspaces_config host=<ip_or_hostname>, apikey=<API_Key>, withtls=F
----
3. 新しいプロジェクトを作成します。
+
NOTE: 現在、Regulus は AWS のみをサポートしています。
+

[source, bash, id="create_project", role="content-editable emits-gtm-events"]
----
%project_create project=<Project_Name>, env=aws
----

4. (オプション) CSP 資格情報を保存するための認可オブジェクトを作成します。
+
`AWS_ACCESS_KEY_ID`、 `AWS_SECRET_ACCESS_KEY`、および `AWS_REGION` を実際の値に置き換えます。
+

[source, bash, id="create_auth", role="content-editable emits-gtm-events"]
----
%project_auth_create name=<Auth_Name>, project=<Project_Name>, key=<AWS_ACCESS_KEY_ID>, secret=<AWS_SECRET_ACCESS_KEy>, region=<AWS_REGION>
----

5. プロジェクトのクエリー エンジンをデプロイします。
+
<Project_Name>をあなたの選んだ名前に置き換えます。サイズパラメータ値には、小、中、大、または特大を指定できます。デフォルトのサイズは小です。
+

[source, bash, id="deploy_query_engine", role="content-editable emits-gtm-events"]
----
%project_engine_deploy name=<Project_Name>, size=<Size_of_Engine>
----

+
展開プロセスが完了するまでに数分かかります。導入が成功すると、パスワードが生成されます。

6. プロジェクトへの接続を確立します。
+

[source, bash, id="connect_project", role="content-editable emits-gtm-events"]
----
%connect <Project_Name>
----
+
接続が確立されると、インターフェイスによってパスワードの入力が求められます。前の手順で生成したパスワードを入力します。

7. サンプル ワークロードを実行します。
+
NOTE: 選択したデータベースに SalesCenter または SalesDemo という名前のテーブルがないことを確認してください。
+
a. 販売センターのデータを保存するテーブルを作成します。
+
まず、テーブルが既に存在する場合は削除します。テーブルが存在しない場合、コマンドは失敗します。
+

[source, teradata-sql, id="create_table", role="content-editable emits-gtm-events"]
----
DROP TABLE SalesCenter;
CREATE MULTISET TABLE SalesCenter ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Sales_Center_id INTEGER NOT NULL,
      Sales_Center_Name VARCHAR(255) CHARACTER SET LATIN NOT CASESPECIFIC)
NO PRIMARY INDEX ;
----

b. `%dataload` マジック コマンドを使用して、SalesCenter テーブルにデータをロードします。
+

[source, bash, id="data_load", role="content-editable emits-gtm-events"]
----
%dataload DATABASE=<Project_Name>, TABLE=SalesCenter, FILEPATH=notebooks/sql/data/salescenter.csv
----
+
データが挿入されたことを確認します。
+

[source, teradata-sql, id="verify_data_load", role="content-editable emits-gtm-events"]
----
SELECT * FROM SalesCenter ORDER BY 1
----

c. 販売デモ データを含むテーブルを作成します。
+

[source, teradata-sql, id="create_table_data", role="content-editable emits-gtm-events"]
----
DROP TABLE SalesDemo;
CREATE MULTISET TABLE SalesDemo ,NO FALLBACK ,
     NO BEFORE JOURNAL,
     NO AFTER JOURNAL,
     CHECKSUM = DEFAULT,
     DEFAULT MERGEBLOCKRATIO
     (
      Sales_Center_ID INTEGER NOT NULL,
      UNITS DECIMAL(15,4),
      SALES DECIMAL(15,2),
      COST DECIMAL(15,2))
NO PRIMARY INDEX ;
----

d. `%dataload` マジック コマンドを使用して、SalesDemo テーブルにデータをロードします。
+

[source, bash, id="load_data_table", role="content-editable emits-gtm-events"]
----
%dataload DATABASE=<Project_Name>, TABLE=SalesDemo, FILEPATH=notebooks/sql/data/salesdemo.csv
----
+
販売デモ データが正常に挿入されたことを確認します。
+
[source, teradata-sql, id="verify_sales_data", role="content-editable emits-gtm-events"]
----
SELECT * FROM SalesDemo ORDER BY sales
----
+
接続のナビゲータを開き、テーブルが作成されたことを確認します。テーブルで行カウントを実行して、データがロードされたことを確認します。

e. グラフ作成のマジックを使用して結果を視覚化します。
+
グラフに X 軸と Y 軸を指定します。
+

[source, bash, id="plot_chart", role="content-editable emits-gtm-events"]
----
%chart sales_center_name, sales, title=Sales Data
----

f.	テーブルを削除します。
+

[source, teradata-sql, id="drop_tables", role="content-editable emits-gtm-events"]
----
DROP TABLE SalesCenter;
DROP TABLE SalesDemo;
----

8. プロジェクトのメタデータとオブジェクト定義を GitHub リポジトリにバックアップします。
+

[source, bash, id="backup_project", role="content-editable emits-gtm-events"]
----
%project_backup project=<Project_Name>
----
9. クエリーエンジンを一時停止します。
+

[source, bash, id="suspend_query_engine", role="content-editable emits-gtm-events"]
----
%project_engine_suspend project=<Project_Name>
----

おめでとうございます！JupyterLab で最初のユースケースが正常に実行されました。

== 次のステップ

* 高度なユースケースを探索することに興味がありますか? 近日公開！GitHub リンクについては、このスペースを引き続き監視してください。

* JupyterLab で利用できるマジック コマンドについて学びます。 xref::jp/regulus/regulus-magic-reference.adoc[]を参照してください。
