name: CI
on:
  workflow_dispatch:
  pull_request:
    types: [opened, edited, reopened, closed, synchronize]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 17
          cache: npm
      - name: Run Antora
        run: ./buildw
      - name: Run PR Preview
        uses: rossjrw/pr-preview-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          preview-branch: gh-pages
          source-dir: build/site
          umbrella-dir: pr-preview
      - run: mkdir /tmp/artifacts    
      - name: Run Lighthouse Report
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: /tmp/artifacts
          urls: 'https://quickstarts.teradata.com,https://quickstarts.teradata.com/nos.html'
          device: 'all' 
      - name: Upload Lighthouse artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
      - name: Leave comment
        uses: foo-software/lighthouse-check-action@master
        with:
          accessToken: ${{ secrets.GITHUB_TOKEN }}
          outputDirectory: /tmp/artifacts
          urls: 'https://quickstarts.teradata.com,https://quickstarts.teradata.com/nos.html'
          device: 'all' 
      - name: Prueba Test Nombre-1
        run: echo ${{ github.event.pull_request.number }}