name: Lighthouse Report
on: [pull_request]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir /tmp/artifacts
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: /tmp/artifacts
          urls: 'https://quickstarts.teradata.com,https://quickstarts.teradata.com/nos.html'
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
      - name: Tets Script
        uses: actions/github-script@v7
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
      - name: Leave Comment
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const github = require('@actions/github');
            const octokit = new github.GitHub(process.env.GITHUB_TOKEN);
            const user = await octokit.users.getAuthenticated();
            console.log(`El token pertenece al usuario: ${user.data.login}`);