name: Lighthouse Report
on: [pull_request]
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: mkdir /tmp/artifacts
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: /tmp/artifacts
          urls: 'https://quickstarts.teradata.com,https://quickstarts.teradata.com/nos.html'
      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts
      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { context: repoContext, github: gh } = require('@actions/github');
            const artifactLink = `${process.env.GITHUB_SERVER_URL}/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}/artifacts`;
            const commentBody = `### Lighthouse Report\n\nThe Lighthouse report is available [here](${artifactLink}).`;
            gh.issues.createComment({
              issue_number: repoContext.issue.number,
              owner: repoContext.repo.owner,
              repo: repoContext.repo.repo,
              body: commentBody
            });