# .github/workflows/preview.yml
name: Deploy PR previews
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize    
jobs:
  deploy-preview-and-lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./buildw
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          preview-branch: gh-pages
          source-dir: build/site
          umbrella-dir: pr-preview
          action: auto
      - run: mkdir /tmp/artifacts
      - name: Test URL
        run: echo "${{ steps.pr-preview.outputs.url }}"
      - name: Run Lighthouse
        uses: foo-software/lighthouse-check-action@master
        with:
          outputDirectory: /tmp/artifacts
          urls: 'https://quickstarts.teradata.com,https://quickstarts.teradata.com/nos.html,${{ steps.pr-preview.outputs.url }}'
      - name: Upload Lighthouse artifacts
        uses: actions/upload-artifact@master
        with:
          name: Lighthouse reports
          path: /tmp/artifacts