# .github/workflows/preview.yml
name: Deploy PR previews
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize    
jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: ./buildw
      - name: Deploy PR Preview
        uses: rossjrw/pr-preview-action@v1.4.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          preview-branch: gh-pages
          source-dir: build/site
          umbrella-dir: pr-preview
          action: auto